version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '7860:7860'
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:7860
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend